language: python
cache:
    pip: true
    directories:
        - $TRAVIS_BUILD_DIR/.hypothesis
python:
    - '3.5'

env:
    matrix:
        - TOXENV=py27-benchmark
        - TOXENV=py27-hashids
        - TOXENV=py27-hypothesis HYPOTHESIS_PROFILE=ci
        - TOXENV=py33-benchmark
        - TOXENV=py33-hashids
        - TOXENV=py33-hypothesis HYPOTHESIS_PROFILE=ci
        - TOXENV=py34-benchmark
        - TOXENV=py34-hashids
        - TOXENV=py34-hypothesis HYPOTHESIS_PROFILE=ci
        - TOXENV=py35-benchmark
        - TOXENV=py35-hashids
        - TOXENV=py35-hypothesis HYPOTHESIS_PROFILE=ci
        - TOXENV=pypy-benchmark
        - TOXENV=pypy-hashids
        - TOXENV=pypy-hypothesis HYPOTHESIS_PROFILE=ci

before_install:
    - |
        if [[ "$TOXENV" == pypy* ]]; then
          export PYENV_ROOT="$HOME/.pyenv"
          if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
            pushd "$PYENV_ROOT" && git pull && popd
          else
            rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
          fi
          export PYPY_VERSION="5.6.0"
          "$PYENV_ROOT/bin/pyenv" install --skip-existing "pypy-$PYPY_VERSION"
          virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
          source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
        fi
install: pip install tox

script: tox
